### ISSUE TITLE
I think there are bugs in your code!

### ISSUE THREAD

**Issue by zhaogengyan** [jms290/NMT#2]
Hello,

I think there are bugs in your code!
For example in the file "NMT_subject_process":

> $ANTSPATH/antsBrainExtraction.sh -d 3 -a ${name}_N4.nii.gz -e ../../NMT.nii.gz -m ../../NMT_brain-mask.nii.gz -o ${name}_

"NMT_brain-mask.nii.gz" should be "NMT_brainmask.nii.gz", right?

and also the first several lines:

> name=$1
> name=$(basename $name)
> if [ "${name#*+*.}" = "HEAD" ] || [ "${name#*+*.}" = "BRIK" ]
> 	then
> 	echo "Converting ${name} to ${name[*]%+*.*}.nii.gz"
> 	3dcalc -a $name -expr 'a' -prefix ${name[*]%+*.*}.nii.gz -overwrite # Convert to nifti if needed
> 	name=${name[*]%+*.*}
> fi
> if [ "${name#*.}" = "nii.gz" ]
> 	then
> 	name=${name[*]%.*.*}
> fi
> if [ "${name#*.}" = "nii" ]
> 	then
> 	name=${name[*]%.*}
> fi

generate bad variable "$name" which makes relative files cannot be found later.

Thanks.

Best,
Gengyan

**Comment by jms290** [comment]
Hi Gengyan,

Thanks for the notification. I can definitely change the NMT_brain-mask.nii.gz to NMT_brainmask.nii.gz. That was probably due to using an older version of the mask.

What exactly is your error for the $name variable?  

Best,

Jakob
