### ISSUE TITLE
Small script adjustment necessary

### ISSUE THREAD

**Issue by pcklink** [jms290/NMT#7]
This is a great tool that is very useful for our lab!

It may, however, be good to know that (at least for bash 4.3 on linux) I had to adjust the `NMT_subject_process` and `NMT_subject_morph` scripts slightly to make them work. In the part that starts with `# Extract name from subject volume file` I had to change instances like `name=${name[*]%.*.*}` to `name=${name%.*.*}` because otherwise, I somehow ended up with unreadable folder names that had weird symbols included in the string. (see this screenshot for example: https://drive.google.com/file/d/1L_fg8_KamxnqKHAQ5YWrPD5On85trlP7/view?usp=sharing)

In addition, it might be good to note somewhere that ANTS requires that the `align_and_process.sh` script is run with Python 2, but maybe I just missed that. I realize that this is not a restriction of the NMT tools, but could still be useful information.

**Comment by Bencephalon** [comment]
Hi Chris,
Thank you for bringing this to our attention. We really appreciate your feedback and have looked into the changes you had to make to get the naming to work. We were unable to replicate the naming error on our systems (bash 4.2.46), but the changes you suggested function equally well, so I've changed the our scripts to reflect your changes.

I'm not sure which script you are referring to when you mention "align_and_process.sh", as I couldn't find this script in our repository nor the ANTs repository. Are you referring to NMT_subject_align.csh and NMT_subject_process?

Best,
Ben

**Comment by pcklink** [comment]
My apologies, the align_and_process.sh script is my own script, adapted from your /single_subject_scans/Example_Subject/align_and_process_tutorial.sh which indeed calls NMT_subject_align.csh and NMT_subject_process.

**Comment by Bencephalon** [comment]
That's odd. I currently utilize Python 3.5.4 and have had no issues with ANTs compatibility. Do you happen to have a copy of the error message that you receive when running align_and_process.sh?

**Comment by pcklink** [comment]
No error message at hand, but if I remember correctly it was one of those classical print"" vs print() errors, where py3 can't handle a py2 print call without parentheses. But perhaps there's something else I need to update...

**Comment by Bencephalon** [comment]
If you happen to come across the python error again, feel free to send me a copy of the error message, and I'll investigate where ANTs is failing and put a warning in our documentation. Again, thank you for your feedback and suggestions.

**Comment by pcklink** [comment]
I checked my software versions. Turns out I needed to update AFNI. Error's gone now. Thanks for looking into it!
